services:
  sql_server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server
    restart: on-failure:5
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Abcd@12345678
    ports:
      - "1433:1433"
    volumes:
      - ./sql-server:/var/opt/mssql/data
